#!/usr/bin/env bash
# install-commands.sh — create the ai-dev-* commands in ~/.local/bin and make
# sure the login shell can find them.
#
# Wrappers, not symlinks: each one records the repository path, so the command
# keeps working from any directory and a moved repository produces a clear
# error instead of a mysterious one. check.sh notices when that path goes bad.
#
# The shell rc file is touched once, inside a single marked block, so repeated
# runs cannot append a second PATH line.
#
#   install-commands.sh [--dry-run] [--verbose] [--no-shell-rc]

set -Eeuo pipefail
. "$(cd -P "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/scripts/lib/common.sh"

NO_RC=0
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)     DRY_RUN=1; shift ;;
    --verbose)     VERBOSE=1; shift ;;
    --no-shell-rc) NO_RC=1; shift ;;
    -h|--help)     printf 'Usage: install-commands.sh [--dry-run] [--no-shell-rc]\n'; exit 0 ;;
    *) die "$EX_FAIL" "Unknown option: $1" ;;
  esac
done

write_wrapper() {
  local name="$1" target="$2"
  local path="$BIN_DIR/$name"
  if is_dry_run; then plan_action LINK "$(tilde "$path")  →  $target"; return 0; fi
  if [ -e "$path" ] && [ ! -f "$path" ]; then
    warn "$(tilde "$path") exists and is not a regular file — left alone"; return 0
  fi
  if [ -f "$path" ] && ! grep -q "$WRAPPER_MARKER" "$path" 2>/dev/null; then
    warn "$(tilde "$path") was not created by this repository — left alone"; return 0
  fi
  cat > "$path" <<WRAPPER
#!/usr/bin/env bash
$WRAPPER_MARKER managed wrapper — regenerated by setup, edits will be lost.
set -Eeuo pipefail
REPO="$REPO_DIR"
if [ ! -x "\$REPO/$target" ]; then
  echo "ai-dev-bootstrap: repository not found at \$REPO" >&2
  echo "Re-run ./bootstrap.sh from the clone to repair this command." >&2
  exit 1
fi
exec "\$REPO/$target" "\$@"
WRAPPER
  chmod +x "$path"
  ok "$name  ${C_DIM}$(tilde "$path")${C_RESET}"
}

ensure_directory "$BIN_DIR"
while IFS='|' read -r name target; do
  [ -n "$name" ] || continue
  write_wrapper "$name" "$target"
done < <(ai_dev_commands)

# --- legacy wrappers from when this repo was OpenCode-only ------------------
for name in $LEGACY_COMMANDS; do
  p="$BIN_DIR/$name"
  [ -f "$p" ] || continue
  grep -q "# opencode-bootstrap" "$p" 2>/dev/null || continue
  if is_dry_run; then plan_action REMOVE "$(tilde "$p")  (superseded)"; continue; fi
  rm -f "$p"
  info "Removed superseded command $name  ${C_DIM}(now ai-dev-sync / ai-dev-doctor)${C_RESET}"
done

[ "$NO_RC" = "1" ] && exit "$EX_OK"

# --- shell rc block ---------------------------------------------------------
# Two things must reach the login shell: ~/.local/bin on PATH, and the
# generated env file carrying MCP credentials into the agents' process
# environment. Both live in one marked block.
RC="$(login_shell_rc 2>/dev/null || true)"
if [ -z "$RC" ]; then
  warn "Unrecognised shell (${SHELL:-unknown}) — add this to your shell config by hand:"
  hint "export PATH=\"\$HOME/.local/bin:\$PATH\""
  hint "[ -f \"$(tilde "$ENV_BRIDGE")\" ] && . \"$(tilde "$ENV_BRIDGE")\""
  exit "$EX_OK"
fi

# Written as a full if/fi so the block never leaves a non-zero status behind as
# the last statement of an rc file.
block="$(cat <<BLOCK
export PATH="$BIN_DIR:\$PATH"
if [ -f "$ENV_BRIDGE" ]; then . "$ENV_BRIDGE"; fi
BLOCK
)"

case "$(printf '%s' "$block" | ensure_block "$RC")" in
  current)      ok "Shell config already current  ${C_DIM}$(tilde "$RC")${C_RESET}" ;;
  created)      ok "Shell config updated  ${C_DIM}$(tilde "$RC")${C_RESET}" ;;
  updated)      ok "Shell config block refreshed  ${C_DIM}$(tilde "$RC")${C_RESET}" ;;
  would-create) plan_action UPDATE "$(tilde "$RC")  (PATH + credential bridge)" ;;
  would-update) plan_action UPDATE "$(tilde "$RC")  (refresh managed block)" ;;
esac

# Retire the block written by the previous generation of this repository.
if [ -f "$RC" ] && grep -qF "$LEGACY_BLOCK_BEGIN" "$RC" 2>/dev/null; then
  if is_dry_run; then plan_action REMOVE "legacy block in $(tilde "$RC")"
  else
    remove_block "$RC" "$LEGACY_BLOCK_BEGIN" "$LEGACY_BLOCK_END"
    info "Removed the superseded opencode-bootstrap block from $(tilde "$RC")"
  fi
fi

if ! path_has_dir "$BIN_DIR"; then
  warn "$(tilde "$BIN_DIR") is not on PATH yet — open a new shell, or run: source $RC"
fi
exit "$EX_OK"
