#!/usr/bin/env bash
# install-mcps.sh — configure the MCP servers from mcp/mcps.json in every agent
# present on this machine, and bridge the credentials they need into the shell.
#
# Two separate jobs, in order:
#   1. Write ~/.config/ai-dev-bootstrap/env.sh (mode 600) from the repo .env.
#      The login shell sources it, so an agent launched from that shell can
#      resolve {env:VAR} at runtime without the key ever entering a config file.
#   2. Hand the manifest to each adapter, which speaks its own agent's dialect.
#
#   install-mcps.sh [--dry-run] [--verbose] [--agent NAME]

set -Eeuo pipefail
. "$(cd -P "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/scripts/lib/common.sh"

ONLY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --verbose) VERBOSE=1; shift ;;
    --agent)   [ $# -ge 2 ] || die "$EX_FAIL" "--agent needs a value"; ONLY="$2"; shift 2 ;;
    --agent=*) ONLY="${1#*=}"; shift ;;
    -h|--help) printf 'Usage: install-mcps.sh [--dry-run] [--agent NAME]\n'; exit 0 ;;
    *) die "$EX_FAIL" "Unknown option: $1" ;;
  esac
done
export DRY_RUN VERBOSE

MANIFEST="$REPO_DIR/mcp/mcps.json"
[ -f "$MANIFEST" ] || die "$EX_CONFIG" "Missing $MANIFEST"
require_cmd node "Install Node.js, then re-run."
validate_json "$MANIFEST" || die "$EX_CONFIG" "$MANIFEST does not parse as JSON"

load_env

# The filesystem server needs a root directory; default to $HOME so a fresh
# machine works with no .env at all.
: "${MCP_FILESYSTEM_ROOT:=$HOME}"
export MCP_FILESYSTEM_ROOT

# --- 1. credential bridge ---------------------------------------------------
if is_dry_run; then
  plan_action CREATE "$(tilde "$ENV_BRIDGE")  (mode 600, credential bridge)"
else
  ensure_directory "$LOCAL_STATE_DIR"
  OLD_UMASK="$(umask)"
  umask 077
  {
    printf '# Generated by ai-dev-bootstrap. Do not edit; edit %s/.env instead.\n' "$REPO_DIR"
    printf 'export MCP_FILESYSTEM_ROOT=%s\n' "$(printf '%q' "$MCP_FILESYSTEM_ROOT")"
    node -e '
      const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
      const vars = new Set();
      for (const e of Object.values(m.servers || {})) {
        for (const v of e.requiresEnv || []) vars.add(v);
        for (const v of e.optionalEnv || []) vars.add(v);
      }
      for (const v of vars) process.stdout.write(v + "\n");
    ' "$MANIFEST" | while IFS= read -r v; do
      [ -n "$v" ] || continue
      eval "val=\${$v:-}"
      # Only variables that actually have a value are written, and the value is
      # quoted, never echoed to the terminal.
      if [ -n "$val" ]; then
        printf 'export %s=%s\n' "$v" "$(printf '%q' "$val")"
      fi
    done
  } > "$ENV_BRIDGE"
  chmod 600 "$ENV_BRIDGE"
  umask "$OLD_UMASK"
  ok "Credential bridge  ${C_DIM}$(tilde "$ENV_BRIDGE") (600)${C_RESET}"
fi

# --- 2. per-agent configuration ---------------------------------------------
for agent in $(adapter_list); do
  [ -n "$ONLY" ] && [ "$ONLY" != "$agent" ] && continue
  label="$(adapter_run "$agent" label)"
  adapter_run "$agent" detect >/dev/null 2>&1 || { info "$label not installed — skipped"; continue; }
  section "$label"
  adapter_run "$agent" mcp-apply
done

# A missing API key is a warning, not a failure: the declarative part of the
# setup succeeded either way.
exit "$EX_OK"
