#!/usr/bin/env bash
# install-mcps.sh — merge the MCP servers declared in mcp/mcps.json into the
# OpenCode global config. Only the named servers are touched; the rest of the
# config is preserved byte-for-byte apart from re-indentation.
#
#   install-mcps.sh [--dry-run]

set -Eeuo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"

DRY_RUN="${DRY_RUN:-0}"
while [ $# -gt 0 ]; do
  case "$1" in --dry-run) DRY_RUN=1; shift ;; *) shift ;; esac
done

has node || die "node not found — required to edit the OpenCode config safely."
load_env

MANIFEST="$REPO_DIR/mcp/mcps.json"
[ -f "$MANIFEST" ] || die "Missing $MANIFEST"

CFG="$(config_file)"
STATE="$MANAGED_DIR/state.json"
SERVERS="$(node -e '
  const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  process.stdout.write(Object.keys(m.servers || {}).join(","));
' "$MANIFEST")"

if [ "$DRY_RUN" = "1" ]; then
  printf '%s\n' "$SERVERS" | tr ',' '\n' | while IFS= read -r s; do
    if [ -n "$s" ]; then info "would configure $s"; fi
  done
  exit 0
fi

# The filesystem server needs an explicit root directory. Default to $HOME so
# a fresh machine works without any .env at all.
: "${MCP_FILESYSTEM_ROOT:=$HOME}"
export MCP_FILESYSTEM_ROOT

mkdir -p "$MANAGED_DIR"
backup_config_dir

# The config references secrets as {env:VAR}, which OpenCode resolves from its
# own process environment -- it has no knowledge of this repository's .env.
# Bridge the two by emitting a shell-sourceable file that the login shell picks
# up (see install-aliases.sh). Mode 0600: it holds real credentials.
ENV_FILE="$MANAGED_DIR/env.sh"
OLD_UMASK="$(umask)"
umask 077
{
  printf '# Generated by opencode-bootstrap. Do not edit; edit %s/.env instead.\n' "$REPO_DIR"
  printf 'export MCP_FILESYSTEM_ROOT=%s\n' "$(printf '%q' "$MCP_FILESYSTEM_ROOT")"
  node -e '
    const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
    const vars = new Set();
    for (const e of Object.values(m.servers || {})) {
      for (const v of e.requiresEnv || []) vars.add(v);
      for (const v of e.optionalEnv || []) vars.add(v);
    }
    for (const v of vars) process.stdout.write(v + "\n");
  ' "$MANIFEST" | while IFS= read -r v; do
    [ -n "$v" ] || continue
    eval "val=\${$v:-}"
    if [ -n "$val" ]; then
      printf 'export %s=%s\n' "$v" "$(printf '%q' "$val")"
    fi
  done
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
umask "$OLD_UMASK"

# stderr carries structured status lines; stdout is unused by `apply`.
err="$(mktemp)"
if ! node "$REPO_DIR/scripts/lib/merge-config.mjs" apply \
      --config "$CFG" --mcp "$MANIFEST" --state "$STATE" --servers "$SERVERS" 2>"$err"; then
  cat "$err" >&2; rm -f "$err"; die "Failed to update $CFG"
fi

# Two passes so the per-server results read as a clean list, with the
# advisories collected underneath rather than interleaved.
while IFS= read -r line; do
  case "$line" in
    applied:*)
      printf '%s\n' "${line#applied:}" | tr ',' '\n' | while IFS= read -r s; do
        if [ -n "$s" ]; then ok "$s"; fi
      done ;;
  esac
done < "$err"

while IFS= read -r line; do
  case "$line" in
    user-owned:*)
      warn "${line#user-owned:} already configured by you — left unchanged" ;;
    removed-stale:*)
      info "removed ${line#removed-stale:} (no longer in manifest)" ;;
    missing-env:*)
      # Payload is "server:VARNAME:required" or "server:VARNAME:optional".
      IFS=':' read -r mserver mvar mkind <<EOF_MISSING
${line#missing-env:}
EOF_MISSING
      if [ "${mkind:-}" = "required" ]; then
        warn "$mserver: \$$mvar is not set — server written disabled so it cannot fail on startup"
      else
        warn "$mserver: \$$mvar is not set — server enabled, but rate-limited/anonymous"
      fi
      hint "Add $mvar to $REPO_DIR/.env, then re-run: opencode-sync" ;;
    comments-dropped:*)
      warn "Comments in $(basename "$CFG") were removed by the rewrite (a backup was taken)" ;;
    unknown-server:*)
      fail "Unknown server in manifest: ${line#unknown-server:}" ;;
  esac
done < "$err"
rm -f "$err"

# MCP servers are declarative config — a missing API key is a warning, not a
# failure, so this always exits 0 unless the config itself could not be written.
exit 0
