#!/usr/bin/env bash
# install-aliases.sh — create the opencode-sync / opencode-doctor commands in
# ~/.local/bin as thin wrappers that point back at this clone.
#
# Wrappers rather than symlinks: they record REPO_DIR, so the commands keep
# working from any cwd and survive the repo being cloned to a custom path.
# The shell rc file is only touched if ~/.local/bin is genuinely missing from
# PATH, and then only by appending a single guarded line.

set -Eeuo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"

DRY_RUN="${DRY_RUN:-0}"
while [ $# -gt 0 ]; do
  case "$1" in --dry-run) DRY_RUN=1; shift ;; *) shift ;; esac
done

MARKER="# opencode-bootstrap"

write_wrapper() {
  local name="$1"
  local target="$2"
  local path="$BIN_DIR/$name"
  if [ "$DRY_RUN" = "1" ]; then info "would create $path"; return 0; fi
  cat > "$path" <<WRAPPER
#!/usr/bin/env bash
$MARKER managed wrapper — regenerated by bootstrap.sh, edits will be lost.
set -Eeuo pipefail
REPO="$REPO_DIR"
if [ ! -x "\$REPO/$target" ]; then
  echo "opencode-bootstrap: repository not found at \$REPO" >&2
  echo "Re-run ./bootstrap.sh from the clone to repair this command." >&2
  exit 1
fi
exec "\$REPO/$target" "\$@"
WRAPPER
  chmod +x "$path"
  ok "$name  ${C_DIM}($path)${C_RESET}"
}

mkdir -p "$BIN_DIR"
write_wrapper opencode-sync   update.sh
write_wrapper opencode-doctor doctor.sh

[ "$DRY_RUN" = "1" ] && exit 0

# --- shell rc block ---------------------------------------------------------
# Two things need to reach the login shell: ~/.local/bin on PATH, and the
# generated env file that carries the MCP API keys into OpenCode's process
# environment. Both go in one marked block so re-running is a no-op and
# uninstall can remove it exactly.

ENV_FILE="$MANAGED_DIR/env.sh"
BEGIN="# >>> opencode-bootstrap >>>"
END="# <<< opencode-bootstrap <<<"

needs_path=1
case ":$PATH:" in *":$BIN_DIR:"*) needs_path=0 ;; esac
[ "$needs_path" = "0" ] && ok "$BIN_DIR is on PATH"

# Pick the rc file from the login shell, not the shell running this script
# (which is always bash).
case "${SHELL:-}" in
  */zsh)  RC="$HOME/.zshrc" ;;
  */bash) RC="$HOME/.bashrc" ;;
  *)      RC="" ;;
esac

if [ -z "$RC" ]; then
  warn "Unrecognised shell (${SHELL:-unknown}) — add this to your shell config by hand:"
  hint "export PATH=\"\$HOME/.local/bin:\$PATH\""
  [ -f "$ENV_FILE" ] && hint ". $ENV_FILE"
  exit 0
fi

# Written as a full if/fi rather than `[ -f x ] && . x` so the block never
# leaves a non-zero status behind as the last statement of the rc file.
block="$BEGIN
export PATH=\"$BIN_DIR:\$PATH\"
if [ -f \"$ENV_FILE\" ]; then . \"$ENV_FILE\"; fi
$END"

if [ -f "$RC" ] && grep -qF "$BEGIN" "$RC"; then
  # Rewrite the existing block in place so an updated BIN_DIR or ENV_FILE
  # takes effect without appending a duplicate.
  tmp="$(mktemp)"
  awk -v b="$BEGIN" -v e="$END" '
    $0 == b { skip = 1 }
    skip != 1 { print }
    $0 == e { skip = 0 }
  ' "$RC" > "$tmp"
  printf '%s\n' "$block" >> "$tmp"
  cat "$tmp" > "$RC"
  rm -f "$tmp"
  ok "Shell config block refreshed  ${C_DIM}($RC)${C_RESET}"
else
  printf '\n%s\n' "$block" >> "$RC"
  ok "Shell config updated  ${C_DIM}($RC)${C_RESET}"
fi

if [ "$needs_path" = "1" ]; then
  warn "$BIN_DIR was not on PATH — open a new shell, or run: source $RC"
else
  hint "Run 'source $RC' so OpenCode picks up the MCP credentials."
fi
exit 0
